// Nepal administrative divisions: 7 provinces, 77 districts, municipalities
// Source: Government of Nepal local level structure (2024)

export const NEPAL_LOCATIONS = {
  "Koshi Province": {
    Bhojpur: [
      "Bhojpur Municipality",
      "Aamchowk Rural Municipality",
      "Arun Rural Municipality",
      "Hatuwagadhi Rural Municipality",
      "Pauwadungma Rural Municipality",
      "Ramprasad Rai Rural Municipality",
      "Salpasilichho Rural Municipality",
      "Shadananda Municipality",
      "Tyamke Maiyum Rural Municipality",
    ],
    Dhankuta: [
      "Dhankuta Municipality",
      "Chaubise Rural Municipality",
      "Chhathar Jorpati Rural Municipality",
      "Khalsa Chhintang Sahidbhumi Rural Municipality",
      "Mahalaxmi Municipality",
      "Pakhribas Municipality",
      "Sangurigadhi Rural Municipality",
    ],
    Ilam: [
      "Ilam Municipality",
      "Deumai Municipality",
      "Mai Municipality",
      "Maijogmai Rural Municipality",
      "Mangsebung Rural Municipality",
      "Phakphokthum Rural Municipality",
      "Rong Rural Municipality",
      "Sandakpur Rural Municipality",
      "Suryodaya Municipality",
    ],
    Jhapa: [
      "Bhadrapur Municipality",
      "Birtamod Municipality",
      "Damak Municipality",
      "Mechinagar Municipality",
      "Arjundhara Municipality",
      "Kankai Municipality",
      "Shivasatakshi Municipality",
      "Gauradaha Municipality",
      "Kamal Rural Municipality",
      "Buddhashanti Rural Municipality",
      "Haldibari Rural Municipality",
      "Jhapa Rural Municipality",
      "Kachankawal Rural Municipality",
      "Barhadashi Rural Municipality",
      "Gaurigunj Rural Municipality",
    ],
    Khotang: [
      "Diktel Rupakot Majhuwagadhi Municipality",
      "Halesi Tuwachung Municipality",
      "Ainselukhark Rural Municipality",
      "Barahapokhari Rural Municipality",
      "Jantedhunga Rural Municipality",
      "Kepilasagadhi Rural Municipality",
      "Khotehang Rural Municipality",
      "Lamidanda Rural Municipality",
      "Rawa Besi Rural Municipality",
      "Sakela Rural Municipality",
    ],
    Morang: [
      "Biratnagar Metropolitan City",
      "Belbari Municipality",
      "Letang Municipality",
      "Pathari Shanishchare Municipality",
      "Rangeli Municipality",
      "Ratuwamai Municipality",
      "Sunbarshi Municipality",
      "Urlabari Municipality",
      "Budhiganga Rural Municipality",
      "Dhanapalthan Rural Municipality",
      "Gramthan Rural Municipality",
      "Jahada Rural Municipality",
      "Kanepokhari Rural Municipality",
      "Katahari Rural Municipality",
      "Kerabari Rural Municipality",
      "Miklajung Rural Municipality",
    ],
    Okhaldhunga: [
      "Siddhicharan Municipality",
      "Champadevi Rural Municipality",
      "Chisankhugadhi Rural Municipality",
      "Khijidemba Rural Municipality",
      "Likhu Rural Municipality",
      "Manebhanjyang Rural Municipality",
      "Molung Rural Municipality",
      "Sunkoshi Rural Municipality",
    ],
    Panchthar: [
      "Phidim Municipality",
      "Falelung Rural Municipality",
      "Falgunanda Rural Municipality",
      "Hilihang Rural Municipality",
      "Kummayak Rural Municipality",
      "Miklajung Rural Municipality",
      "Tumbewa Rural Municipality",
      "Yangwarak Rural Municipality",
    ],
    Sankhuwasabha: [
      "Khandbari Municipality",
      "Chainpur Municipality",
      "Dharmadevi Municipality",
      "Madi Municipality",
      "Panchkhapan Municipality",
      "Bhotkhola Rural Municipality",
      "Chichila Rural Municipality",
      "Makalu Rural Municipality",
      "Silichong Rural Municipality",
      "Sabhapokhari Rural Municipality",
    ],
    Solukhumbu: [
      "Salleri Dudhkoshi Rural Municipality",
      "Solu Dudhkunda Municipality",
      "Khumbu Pasanglhamu Rural Municipality",
      "Likhu Pike Rural Municipality",
      "Mahakulung Rural Municipality",
      "Nechasalyan Rural Municipality",
      "Thulung Dudhkoshi Rural Municipality",
    ],
    Sunsari: [
      "Itahari Sub-Metropolitan City",
      "Dharan Sub-Metropolitan City",
      "Inaruwa Municipality",
      "Duhabi Municipality",
      "Ramdhuni Municipality",
      "Barahachhetra Municipality",
      "Barju Rural Municipality",
      "Bhokraha Narsingh Rural Municipality",
      "Dewangunj Rural Municipality",
      "Gadhi Rural Municipality",
      "Harinagara Rural Municipality",
      "Koshi Rural Municipality",
    ],
    Taplejung: [
      "Phungling Municipality",
      "Aathrai Tribeni Rural Municipality",
      "Maiwakhola Rural Municipality",
      "Meringden Rural Municipality",
      "Mikwakhola Rural Municipality",
      "Phaktanglung Rural Municipality",
      "Sidingba Rural Municipality",
      "Sirijunga Rural Municipality",
      "Yangwarak Rural Municipality",
    ],
    Terhathum: [
      "Myanglung Municipality",
      "Laligurans Municipality",
      "Aathrai Rural Municipality",
      "Chhathar Rural Municipality",
      "Menchhayayem Rural Municipality",
      "Phedap Rural Municipality",
    ],
    Udayapur: [
      "Katari Municipality",
      "Triyuga Municipality",
      "Chaudandigadhi Municipality",
      "Belaka Municipality",
      "Rautamai Rural Municipality",
      "Sunkoshi Rural Municipality",
      "Tapli Rural Municipality",
      "Udayapurgadhi Rural Municipality",
    ],
  },

  "Madhesh Province": {
    Bara: [
      "Kalaiya Sub-Metropolitan City",
      "Jitpur Simara Sub-Metropolitan City",
      "Kolhabi Municipality",
      "Nijgadh Municipality",
      "Simraungadh Municipality",
      "Pacharauta Municipality",
      "Mahagadhimai Municipality",
      "Adarshkotwal Rural Municipality",
      "Baragadhi Rural Municipality",
      "Devtal Rural Municipality",
      "Karaiyamai Rural Municipality",
      "Parwanipur Rural Municipality",
      "Pheta Rural Municipality",
      "Prasauni Rural Municipality",
      "Suwarna Rural Municipality",
    ],
    Dhanusha: [
      "Janakpurdham Sub-Metropolitan City",
      "Dhanushadham Municipality",
      "Ganeshman Charnath Municipality",
      "Mithila Municipality",
      "Nagarain Municipality",
      "Sabaila Municipality",
      "Aurahi Rural Municipality",
      "Bateshwor Rural Municipality",
      "Dhanauji Rural Municipality",
      "Hansapur Rural Municipality",
      "Janaknandini Rural Municipality",
      "Kamala Municipality",
      "Laxminiya Rural Municipality",
      "Mithila Bihari Municipality",
      "Mukhiyapatti Musaharniya Rural Municipality",
      "Sakhuwa Nankarkatti Rural Municipality",
      "Tulsiyahi Rural Municipality",
    ],
    Mahottari: [
      "Jaleshwor Municipality",
      "Bardibas Municipality",
      "Gaushala Municipality",
      "Loharpatti Municipality",
      "Ramgopalpur Municipality",
      "Aurahi Municipality",
      "Balawa Municipality",
      "Bhangaha Municipality",
      "Ekdanra Rural Municipality",
      "Mahottari Rural Municipality",
      "Manra Siswa Municipality",
      "Matihani Municipality",
      "Pipra Rural Municipality",
      "Samsi Rural Municipality",
      "Sonama Rural Municipality",
    ],
    Parsa: [
      "Birgunj Metropolitan City",
      "Pokhariya Municipality",
      "Bahudarmai Municipality",
      "Parsagadhi Municipality",
      "Thori Rural Municipality",
      "Bindabasini Rural Municipality",
      "Chhipaharmai Rural Municipality",
      "Dhobini Rural Municipality",
      "Jagarnathpur Rural Municipality",
      "Jirabhawani Rural Municipality",
      "Kalikamai Rural Municipality",
      "Pakaha Mainpur Rural Municipality",
      "Paterwa Sugauli Rural Municipality",
      "Sakhuwa Prasauni Rural Municipality",
    ],
    Rautahat: [
      "Gaur Municipality",
      "Garuda Municipality",
      "Chandrapur Municipality",
      "Ishnath Municipality",
      "Katahariya Municipality",
      "Madhav Narayan Municipality",
      "Maulapur Municipality",
      "Phatuwa Bijaypur Municipality",
      "Rajdevi Municipality",
      "Rajpur Municipality",
      "Brindaban Municipality",
      "Dewahi Gonahi Municipality",
      "Durga Bhagwati Rural Municipality",
      "Gadhimai Municipality",
      "Gujara Municipality",
      "Yamunamai Rural Municipality",
    ],
    Saptari: [
      "Rajbiraj Municipality",
      "Hanumannagar Kankalini Municipality",
      "Kanchanrup Municipality",
      "Khadak Municipality",
      "Saptakoshi Rural Municipality",
      "Shambhunath Municipality",
      "Surunga Municipality",
      "Agnisair Krishna Sabaran Rural Municipality",
      "Balan Bihul Rural Municipality",
      "Bishnupur Rural Municipality",
      "Chhinnamasta Rural Municipality",
      "Mahadeva Rural Municipality",
      "Rupani Rural Municipality",
      "Tilathi Koiladi Rural Municipality",
      "Tirhut Rural Municipality",
    ],
    Sarlahi: [
      "Malangwa Municipality",
      "Haripur Municipality",
      "Haripurwa Municipality",
      "Hariwan Municipality",
      "Ishwarpur Municipality",
      "Kabilasi Municipality",
      "Lalbandi Municipality",
      "Bagmati Municipality",
      "Balara Municipality",
      "Barahathwa Municipality",
      "Basbariya Rural Municipality",
      "Brahmapuri Rural Municipality",
      "Chakraghatta Rural Municipality",
      "Chandranagar Rural Municipality",
      "Dhankaul Rural Municipality",
      "Kaudena Rural Municipality",
      "Parsa Rural Municipality",
      "Ramnagar Rural Municipality",
    ],
    Siraha: [
      "Lahan Municipality",
      "Siraha Municipality",
      "Dhangadhimai Municipality",
      "Golbazar Municipality",
      "Mirchaiya Municipality",
      "Aurahi Rural Municipality",
      "Bariyarpatti Rural Municipality",
      "Bhagwanpur Rural Municipality",
      "Bishnupur Rural Municipality",
      "Kalyanpur Municipality",
      "Karjanha Municipality",
      "Laxmipur Patari Rural Municipality",
      "Naraha Rural Municipality",
      "Nawarajpur Rural Municipality",
      "Sakhuwanankarkatti Rural Municipality",
      "Sukhipur Rural Municipality",
    ],
  },

  "Bagmati Province": {
    Bhaktapur: [
      "Bhaktapur Municipality",
      "Changunarayan Municipality",
      "Madhyapur Thimi Municipality",
      "Suryabinayak Municipality",
    ],
    Chitwan: [
      "Bharatpur Metropolitan City",
      "Ratnanagar Municipality",
      "Kalika Municipality",
      "Khairahani Municipality",
      "Madi Municipality",
      "Rapti Municipality",
      "Ichchhakamana Rural Municipality",
    ],
    Dhading: [
      "Dhading Besi Municipality",
      "Benighat Rorang Rural Municipality",
      "Gajuri Rural Municipality",
      "Galchhi Rural Municipality",
      "Gangajamuna Rural Municipality",
      "Jwalamukhi Rural Municipality",
      "Khaniyabas Rural Municipality",
      "Netrabati Gonaga Rural Municipality",
      "Nilkantha Municipality",
      "Rubi Valley Rural Municipality",
      "Siddhalek Rural Municipality",
      "Thakre Rural Municipality",
      "Tripurasundari Rural Municipality",
    ],
    Dolakha: [
      "Bhimeshwor Municipality",
      "Jiri Municipality",
      "Baiteshwor Rural Municipality",
      "Bigu Rural Municipality",
      "Gaurishankar Rural Municipality",
      "Kalinchok Rural Municipality",
      "Melung Rural Municipality",
      "Shailung Rural Municipality",
      "Tamakoshi Rural Municipality",
    ],
    Kathmandu: [
      "Kathmandu Metropolitan City",
      "Kirtipur Municipality",
      "Tokha Municipality",
      "Nagarjun Municipality",
      "Kageshwori Manohara Municipality",
      "Budhanilkantha Municipality",
      "Shankharapur Municipality",
      "Tarakeshwar Municipality",
      "Dakshinkali Municipality",
      "Chandragiri Municipality",
      "Gokarneshwar Municipality",
    ],
    Kavrepalanchok: [
      "Banepa Municipality",
      "Dhulikhel Municipality",
      "Panauti Municipality",
      "Panchkhal Municipality",
      "Mandandeupur Municipality",
      "Bethanchowk Rural Municipality",
      "Bhumlu Rural Municipality",
      "Chaurideurali Rural Municipality",
      "Khanikhola Rural Municipality",
      "Mahabharat Rural Municipality",
      "Namobuddha Municipality",
      "Roshi Rural Municipality",
      "Temal Rural Municipality",
    ],
    Lalitpur: [
      "Lalitpur Metropolitan City",
      "Godawari Municipality",
      "Mahalaxmi Municipality",
      "Konjyosom Rural Municipality",
      "Bagmati Rural Municipality",
      "Mahankal Rural Municipality",
    ],
    Makwanpur: [
      "Hetauda Sub-Metropolitan City",
      "Thaha Municipality",
      "Bhimphedi Rural Municipality",
      "Bakaiya Rural Municipality",
      "Bagmati Rural Municipality",
      "Indrasarowar Rural Municipality",
      "Kailash Rural Municipality",
      "Makawanpurgadhi Rural Municipality",
      "Manahari Rural Municipality",
      "Raksirang Rural Municipality",
    ],
    Nuwakot: [
      "Bidur Municipality",
      "Belkotgadhi Municipality",
      "Dupcheshwor Rural Municipality",
      "Kakani Rural Municipality",
      "Kispang Rural Municipality",
      "Likhu Rural Municipality",
      "Meghang Rural Municipality",
      "Panchakanya Rural Municipality",
      "Shivapuri Rural Municipality",
      "Suryagadhi Rural Municipality",
      "Tadi Rural Municipality",
      "Tarkeshwor Rural Municipality",
    ],
    Ramechhap: [
      "Manthali Municipality",
      "Ramechhap Municipality",
      "Doramba Rural Municipality",
      "Gokulganga Rural Municipality",
      "Khandadevi Rural Municipality",
      "Likhu Rural Municipality",
      "Sunapati Rural Municipality",
      "Umakunda Rural Municipality",
    ],
    Rasuwa: [
      "Gosaikunda Rural Municipality",
      "Kalika Rural Municipality",
      "Naukunda Rural Municipality",
      "Parbatikunda Rural Municipality",
      "Uttargaya Rural Municipality",
    ],
    Sindhuli: [
      "Kamalamai Municipality",
      "Dudhauli Municipality",
      "Golanjor Rural Municipality",
      "Ghyanglekh Rural Municipality",
      "Hariharpurgadhi Rural Municipality",
      "Marin Rural Municipality",
      "Phikkal Rural Municipality",
      "Sunkoshi Rural Municipality",
      "Tinpatan Rural Municipality",
    ],
    Sindhupalchok: [
      "Chautara Sangachokgadhi Municipality",
      "Barhabise Municipality",
      "Melamchi Municipality",
      "Balephi Rural Municipality",
      "Bhotekoshi Rural Municipality",
      "Helambu Rural Municipality",
      "Indrawati Rural Municipality",
      "Jugal Rural Municipality",
      "Lisankhu Pakhar Rural Municipality",
      "Panchpokhari Thangpal Rural Municipality",
      "Sunkoshi Rural Municipality",
      "Tripurasundari Rural Municipality",
    ],
  },

  "Gandaki Province": {
    Baglung: [
      "Baglung Municipality",
      "Galkot Municipality",
      "Jaimuni Municipality",
      "Dhorpatan Municipality",
      "Bareng Rural Municipality",
      "Badigad Rural Municipality",
      "Kanthekhola Rural Municipality",
      "Nisikhola Rural Municipality",
      "Tarakhola Rural Municipality",
      "Taman Khola Rural Municipality",
    ],
    Gorkha: [
      "Gorkha Municipality",
      "Palungtar Municipality",
      "Barpak Sulikot Rural Municipality",
      "Ajirkot Rural Municipality",
      "Aarughat Rural Municipality",
      "Bhimsen Rural Municipality",
      "Chumanubri Rural Municipality",
      "Dharche Rural Municipality",
      "Gandaki Rural Municipality",
      "Sahid Lakhan Rural Municipality",
      "Siranchok Rural Municipality",
    ],
    Kaski: [
      "Pokhara Metropolitan City",
      "Annapurna Rural Municipality",
      "Machhapuchhre Rural Municipality",
      "Madi Rural Municipality",
      "Rupa Rural Municipality",
    ],
    Lamjung: [
      "Besisahar Municipality",
      "Sundarbazar Municipality",
      "Madhya Nepal Municipality",
      "Rainas Municipality",
      "Dordi Rural Municipality",
      "Dudhpokhari Rural Municipality",
      "Kwholasothar Rural Municipality",
      "Marsyangdi Rural Municipality",
    ],
    Manang: [
      "Chame Rural Municipality",
      "Narpa Bhumi Rural Municipality",
      "Nashong Rural Municipality",
      "Manang Ngisyang Rural Municipality",
    ],
    Mustang: [
      "Gharpajhong Rural Municipality",
      "Thasang Rural Municipality",
      "Baragung Muktichhetra Rural Municipality",
      "Lomanthang Rural Municipality",
      "Lo-Ghekar Damodarkunda Rural Municipality",
    ],
    Myagdi: [
      "Beni Municipality",
      "Annapurna Rural Municipality",
      "Dhawalagiri Rural Municipality",
      "Malika Rural Municipality",
      "Mangala Rural Municipality",
      "Raghuganga Rural Municipality",
    ],
    Nawalpur: [
      "Kawasoti Municipality",
      "Gaindakot Municipality",
      "Devchuli Municipality",
      "Madhyabindu Municipality",
      "Bulingtar Rural Municipality",
      "Bungdikali Rural Municipality",
      "Hupsekot Rural Municipality",
      "Binayi Tribeni Rural Municipality",
    ],
    Parbat: [
      "Kushma Municipality",
      "Phalebas Municipality",
      "Jaljala Rural Municipality",
      "Paiyu Rural Municipality",
      "Mahashila Rural Municipality",
      "Modi Rural Municipality",
    ],
    Syangja: [
      "Putalibazar Municipality",
      "Waling Municipality",
      "Galyang Municipality",
      "Chapakot Municipality",
      "Bhirkot Municipality",
      "Arjun Chaupari Rural Municipality",
      "Aandhikhola Rural Municipality",
      "Kaligandaki Rural Municipality",
      "Phedikhola Rural Municipality",
      "Harinas Rural Municipality",
      "Biruwa Rural Municipality",
    ],
    Tanahun: [
      "Bhanu Municipality",
      "Bhimad Municipality",
      "Byas Municipality",
      "Shuklagandaki Municipality",
      "Bandipur Rural Municipality",
      "Anbukhaireni Rural Municipality",
      "Devghat Rural Municipality",
      "Ghiring Rural Municipality",
      "Myagde Rural Municipality",
      "Rhishing Rural Municipality",
    ],
  },

  "Lumbini Province": {
    Arghakhanchi: [
      "Sandhikharka Municipality",
      "Sitganga Municipality",
      "Bhumikasthan Municipality",
      "Chhatradev Rural Municipality",
      "Malarani Rural Municipality",
      "Pandav Gupha Rural Municipality",
      "Panini Rural Municipality",
    ],
    Banke: [
      "Nepalgunj Sub-Metropolitan City",
      "Kohalpur Municipality",
      "Narainapur Rural Municipality",
      "Rapti Sonari Rural Municipality",
      "Baijanath Rural Municipality",
      "Khajura Rural Municipality",
      "Duduwa Rural Municipality",
      "Janaki Rural Municipality",
    ],
    Bardiya: [
      "Gulariya Municipality",
      "Rajapur Municipality",
      "Madhuwan Municipality",
      "Thakurbaba Municipality",
      "Bansgadhi Municipality",
      "Barbardiya Municipality",
      "Geruwa Rural Municipality",
      "Badhaiyatal Rural Municipality",
    ],
    Dang: [
      "Ghorahi Sub-Metropolitan City",
      "Tulsipur Sub-Metropolitan City",
      "Lamahi Municipality",
      "Banglachuli Rural Municipality",
      "Dangisharan Rural Municipality",
      "Gadhawa Rural Municipality",
      "Rajpur Rural Municipality",
      "Rapti Rural Municipality",
      "Shantinagar Rural Municipality",
      "Babai Rural Municipality",
    ],
    Gulmi: [
      "Resunga Municipality",
      "Musikot Municipality",
      "Chandrakot Rural Municipality",
      "Dhurkot Rural Municipality",
      "Gulmidarbar Rural Municipality",
      "Isma Rural Municipality",
      "Kaligandaki Rural Municipality",
      "Madane Rural Municipality",
      "Malika Rural Municipality",
      "Ruru Rural Municipality",
      "Satyawati Rural Municipality",
    ],
    Kapilvastu: [
      "Kapilvastu Municipality",
      "Banganga Municipality",
      "Buddhabhumi Municipality",
      "Shivaraj Municipality",
      "Maharajgunj Municipality",
      "Krishnanagar Municipality",
      "Mayadevi Rural Municipality",
      "Yashodhara Rural Municipality",
      "Suddhodhan Rural Municipality",
      "Bijayanagar Rural Municipality",
    ],
    "Nawalparasi West": [
      "Ramgram Municipality",
      "Sunwal Municipality",
      "Bardaghat Municipality",
      "Sarawal Rural Municipality",
      "Palhi Nandan Rural Municipality",
      "Pratappur Rural Municipality",
      "Susta Rural Municipality",
    ],
    Palpa: [
      "Tansen Municipality",
      "Rampur Municipality",
      "Rainadevi Chhahara Rural Municipality",
      "Ribdikot Rural Municipality",
      "Bagnaskali Rural Municipality",
      "Rambha Rural Municipality",
      "Purbakhola Rural Municipality",
      "Nisdi Rural Municipality",
      "Mathagadhi Rural Municipality",
      "Tinau Rural Municipality",
    ],
    Pyuthan: [
      "Pyuthan Municipality",
      "Sworgadwary Municipality",
      "Gaumukhi Rural Municipality",
      "Mallarani Rural Municipality",
      "Mandavi Rural Municipality",
      "Naubahini Rural Municipality",
      "Jhimruk Rural Municipality",
      "Sarumarani Rural Municipality",
      "Ayirabati Rural Municipality",
    ],
    Rolpa: [
      "Rolpa Municipality",
      "Triveni Rural Municipality",
      "Duikholi Rural Municipality",
      "Madi Rural Municipality",
      "Runtigadhi Rural Municipality",
      "Lungri Rural Municipality",
      "Sunchhahari Rural Municipality",
      "Thawang Rural Municipality",
      "Paribartan Rural Municipality",
      "Gangadev Rural Municipality",
    ],
    "Rukum East": [
      "Putha Uttanganga Rural Municipality",
      "Bhume Rural Municipality",
      "Sisne Rural Municipality",
    ],
    Rupandehi: [
      "Butwal Sub-Metropolitan City",
      "Siddharthanagar Municipality",
      "Tilottama Municipality",
      "Devdaha Municipality",
      "Lumbini Sanskritik Municipality",
      "Sainamaina Municipality",
      "Gaidahawa Rural Municipality",
      "Kanchan Rural Municipality",
      "Kotahimai Rural Municipality",
      "Marchawari Rural Municipality",
      "Mayadevi Rural Municipality",
      "Omsatiya Rural Municipality",
      "Rohini Rural Municipality",
      "Sammarimai Rural Municipality",
      "Siyari Rural Municipality",
      "Suddhodhan Rural Municipality",
    ],
  },

  "Karnali Province": {
    Dailekh: [
      "Narayan Municipality",
      "Dullu Municipality",
      "Chamunda Bindrasaini Municipality",
      "Aathabis Municipality",
      "Gurans Rural Municipality",
      "Bhagawatimai Rural Municipality",
      "Naumule Rural Municipality",
      "Mahabu Rural Municipality",
      "Thantikandh Rural Municipality",
      "Bhairabi Rural Municipality",
      "Dungeshwor Rural Municipality",
    ],
    Dolpa: [
      "Thuli Bheri Municipality",
      "Tripurasundari Municipality",
      "Dolpo Buddha Rural Municipality",
      "Chharka Tangsong Rural Municipality",
      "Jagadulla Rural Municipality",
      "Kaike Rural Municipality",
      "Mudkechula Rural Municipality",
      "Shey Phoksundo Rural Municipality",
    ],
    Humla: [
      "Simkot Rural Municipality",
      "Namkha Rural Municipality",
      "Kharpunath Rural Municipality",
      "Sarkegad Rural Municipality",
      "Chankheli Rural Municipality",
      "Adanchuli Rural Municipality",
      "Tanjakot Rural Municipality",
    ],
    Jajarkot: [
      "Bheri Municipality",
      "Chhedagad Municipality",
      "Nalgad Municipality",
      "Junichande Rural Municipality",
      "Kuse Rural Municipality",
      "Barekot Rural Municipality",
      "Shivalaya Rural Municipality",
    ],
    Jumla: [
      "Chandannath Municipality",
      "Tila Rural Municipality",
      "Guthichaur Rural Municipality",
      "Kanakasundari Rural Municipality",
      "Patarasi Rural Municipality",
      "Tatopani Rural Municipality",
      "Hima Rural Municipality",
      "Sinja Rural Municipality",
    ],
    Kalikot: [
      "Khandachakra Municipality",
      "Raskot Municipality",
      "Tilagupha Municipality",
      "Narharinath Rural Municipality",
      "Palata Rural Municipality",
      "Shubha Kalika Rural Municipality",
      "Sanni Triveni Rural Municipality",
      "Pachaljharana Rural Municipality",
      "Mahawai Rural Municipality",
    ],
    Mugu: [
      "Chhayanath Rara Municipality",
      "Mugum Karmarong Rural Municipality",
      "Soru Rural Municipality",
      "Khatyad Rural Municipality",
    ],
    "Rukum West": [
      "Musikot Municipality",
      "Chaurjahari Municipality",
      "Aathbiskot Municipality",
      "Tribeni Rural Municipality",
      "Banphikot Rural Municipality",
      "Sanibheri Rural Municipality",
    ],
    Salyan: [
      "Sharada Municipality",
      "Bagchaur Municipality",
      "Bangad Kupinde Municipality",
      "Kalimati Rural Municipality",
      "Tribeni Rural Municipality",
      "Kapurkot Rural Municipality",
      "Chhatreshwori Rural Municipality",
      "Dhorchaur Rural Municipality",
      "Kumakh Rural Municipality",
      "Darma Rural Municipality",
    ],
    Surkhet: [
      "Birendranagar Municipality",
      "Bheriganga Municipality",
      "Gurbhakot Municipality",
      "Lekbeshi Municipality",
      "Panchapuri Municipality",
      "Barahatal Rural Municipality",
      "Chingad Rural Municipality",
      "Chaukune Rural Municipality",
      "Simta Rural Municipality",
    ],
  },

  "Sudurpashchim Province": {
    Achham: [
      "Mangalsen Municipality",
      "Sanfebagar Municipality",
      "Kamalbazar Municipality",
      "Panchadewal Binayak Municipality",
      "Chaurpati Rural Municipality",
      "Mellekh Rural Municipality",
      "Bannigadhi Jayagadh Rural Municipality",
      "Dhakari Rural Municipality",
      "Turmakhad Rural Municipality",
      "Ramaroshan Rural Municipality",
    ],
    Baitadi: [
      "Dasharathchand Municipality",
      "Patan Municipality",
      "Melauli Municipality",
      "Purchaudi Municipality",
      "Surnaya Rural Municipality",
      "Sigas Rural Municipality",
      "Shivanath Rural Municipality",
      "Pancheshwor Rural Municipality",
      "Dogada Kedar Rural Municipality",
      "Dilashaini Rural Municipality",
    ],
    Bajhang: [
      "Jaya Prithvi Municipality",
      "Bungal Municipality",
      "Talkot Rural Municipality",
      "Masta Rural Municipality",
      "Khaptad Chhededaha Rural Municipality",
      "Thalara Rural Municipality",
      "Bitthadchir Rural Municipality",
      "Surma Rural Municipality",
      "Saipal Rural Municipality",
      "Durgathali Rural Municipality",
      "Kedarsyu Rural Municipality",
      "Chhabis Pathibhera Rural Municipality",
    ],
    Bajura: [
      "Badimalika Municipality",
      "Triveni Municipality",
      "Budhiganga Municipality",
      "Budhinanda Municipality",
      "Gaumul Rural Municipality",
      "Jagannath Rural Municipality",
      "Swami Kartik Khapar Rural Municipality",
      "Khaptad Chhededaha Rural Municipality",
      "Himali Rural Municipality",
    ],
    Dadeldhura: [
      "Amargadhi Municipality",
      "Parshuram Municipality",
      "Ajaymeru Rural Municipality",
      "Bhageshwor Rural Municipality",
      "Nawadurga Rural Municipality",
      "Ganyapdhura Rural Municipality",
      "Alital Rural Municipality",
    ],
    Darchula: [
      "Mahakali Municipality",
      "Shailyashikhar Municipality",
      "Malikarjun Rural Municipality",
      "Apihimal Rural Municipality",
      "Duhun Rural Municipality",
      "Naugad Rural Municipality",
      "Marma Rural Municipality",
      "Lekam Rural Municipality",
      "Byas Rural Municipality",
    ],
    Doti: [
      "Dipayal Silgadhi Municipality",
      "Shikhar Municipality",
      "Aadarsha Rural Municipality",
      "Purbichauki Rural Municipality",
      "K.I. Singh Rural Municipality",
      "Bogatan Rural Municipality",
      "Jorayal Rural Municipality",
      "Sayal Rural Municipality",
      "Badikedar Rural Municipality",
    ],
    Kailali: [
      "Dhangadhi Sub-Metropolitan City",
      "Tikapur Municipality",
      "Ghodaghodi Municipality",
      "Lamki Chuha Municipality",
      "Bhajani Municipality",
      "Godawari Municipality",
      "Gauriganga Municipality",
      "Janaki Rural Municipality",
      "Joshipur Rural Municipality",
      "Bardagoriya Rural Municipality",
      "Mohanyal Rural Municipality",
      "Chure Rural Municipality",
      "Kailari Rural Municipality",
    ],
    Kanchanpur: [
      "Bhimdatta Municipality",
      "Punarbas Municipality",
      "Bedkot Municipality",
      "Mahakali Municipality",
      "Shuklaphanta Municipality",
      "Belauri Municipality",
      "Krishnapur Municipality",
      "Laljhadi Rural Municipality",
      "Beldandi Rural Municipality",
    ],
  },
};

export const PROVINCE_NAMES = Object.keys(NEPAL_LOCATIONS);

export function getDistricts(province) {
  if (!province || !NEPAL_LOCATIONS[province]) return [];
  return Object.keys(NEPAL_LOCATIONS[province]).sort();
}

export function getCities(province, district) {
  if (!province || !district) return [];
  return NEPAL_LOCATIONS[province]?.[district] ?? [];
}
